apiVersion: v1
kind: Service
metadata: 
  name: hello-holz-service


spec: 
  type: LoadBalancer  # it was ---> NodePort
  ports:
    - port: 3000
      targetPort: 3000
      # nodePort: 30009  You can remove nodePort because LoadBalancer will handle it
  selector:
      type: proj1